# Generated by Django 3.2 on 2023-02-07 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Date_and_Time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Start_Time', models.DecimalField(decimal_places=2, max_digits=2)),
                ('End_Time', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
