# Generated by Django 3.2 on 2023-02-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='End_Time',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='Start_Time',
        ),
    ]
