# Generated by Django 3.2 on 2023-02-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20230208_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
